import {defineConfig} from "vite";
import path from "path";
const config = defineConfig({
    build: {
        lib: {
            entry: path.resolve(__dirname, 'index.ts'),
            name: "http-client-ts",
            formats: ['es', 'umd','cjs'], // adding 'umd' requires globals set to every external module
            fileName: (format) => `http-client-ts.${format}.js`,
        },
        rollupOptions: {
            // 预依赖(peerDependencies)的模块不要打包到库中
            //external: ['axios','luch-request','']
        },
        emptyOutDir: false, // to retain the types folder generated by tsc
    },
});


export default config
